name: Release Orange Pi Zero3 DTB

on:
  push:
    tags:
      - 'orangepi_zero3*'

jobs:
  build-dtb-orangepi_zero3:
    uses: ./.github/workflows/build_dtb_base_workflow.yml
    with:
      tgt: orangepi_zero3

  release-dtb-orangepi_zero3:
    runs-on: ubuntu-latest
    needs: [build-dtb-orangepi_zero3]
    steps:
      # Checkout the repository, this is needed for 'gh' to work
      - uses: actions/checkout@v3

      - name: Download dtb_orangepi_zero3 release file
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 #v3.0.0
        with:
          name: dtb_orangepi_zero3

      - name: Create Orange Pi Zero3 Release
        id: create_release
        run: |
          tag_name=$(echo "${GITHUB_REF#refs/tags/}")
          body="Release notes for $tag_name"
          
          echo "Creating release $tag_name"
          gh release create "$tag_name" "${GITHUB_WORKSPACE}/dtb_orangepi_zero3.dtb" --notes "$body"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Verify Release
        run: |
          release_id=$(gh release view "$tag_name" --json id -q ".[0].id")
          echo "Release ID: $release_id"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
