name: Release NanoPi R4S DTB

on:
  push:
    tags:
      - 'nanopi-r4s*'

jobs:
  build-dtb-nanopi-r4s:
    uses: ./.github/workflows/build_dtb_base_workflow.yml
    with:
      tgt: nanopi-r4s

  release-dtb-nanopi-r4s:
    runs-on: ubuntu-latest
    needs: [build-dtb-nanopi-r4s]
    steps:
      # Checkout the repository, this is needed for 'gh' to work
      - uses: actions/checkout@v3

      - name: Download dtb_nanopi-r4s release file
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a #v3.0.2
        with:
          name: dtb_nanopi-r4s

      - name: Create NanoPi R4S Release
        id: create_release
        run: |
          tag_name=$(echo "${GITHUB_REF#refs/tags/}")
          body="Release notes for $tag_name"
          
          echo "Creating release $tag_name"
          gh release create "$tag_name" "${GITHUB_WORKSPACE}/dtb_nanopi-r4s.dtb" --notes "$body"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Verify Release
        run: |
          release_id=$(gh release view "$tag_name" --json id -q ".id")
          echo "Release ID: $release_id"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
